CREATE TABLE G77_CFG.T_DMP_USE_CASE_CONFIG 
    (USE_CASE_ID			  VARCHAR2(240 BYTE) NOT NULL
    ,USE_CASE_DESCRIPTION	  VARCHAR2(500 BYTE)
    ,FREQUENCY                VARCHAR2(500 BYTE)
    ,DQ_TABLE_NAME            VARCHAR2(200 BYTE)
    ,USE_CASE_CATEGORY        VARCHAR2(200 BYTE) NOT NULL
    ,GATEWAY_ID               NUMBER   GENERATED ALWAYS AS IDENTITY
    ,CONSTRAINT PK_T_DMP_USE_CASE_CONFIG PRIMARY KEY (GATEWAY_ID)
);
