CREATE TABLE G77_CFG.T_MAP_SRC_TRG_WF_DATA
(
  METADATA_ID    NUMBER                         NOT NULL,
  MODIFIED_BY    VARCHAR2(100 CHAR),
  MODIFIED_TIME  DATE,
  CONSTRAINT PK_T_MAP_SRC_TRG_WF_DATA PRIMARY KEY (METADATA_ID)
);