CREATE OR REPLACE TRIGGER G77_CFG.TR_T_ERROR_LOG_ACTIV_IND
BEFORE INSERT
ON G77_CFG.T_ERROR_LOG REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  IF :new.ERROR_ACTIVE_IND IS NULL THEN
     :new.ERROR_ACTIVE_IND := 'A';
  END IF;
END;
/