create or replace TYPE DQ_USER.BATCH_STATUS_TYPE FORCE AS OBJECT
    (USE_CASE_ID                   VARCHAR2(200)
    ,BATCH_TASK_SESSION_ID         VARCHAR2(200)
    ,BATCH_GROUP                   VARCHAR2(500)
    ,BATCH_TASK_APTITUDE_MICROFLOW VARCHAR2(500)
    ,DMP_ORDER                     NUMBER
    ,CURRENT_RUN_STATUS            VARCHAR2(50)
    ,ORIGINAL_RUN_STATUS           VARCHAR2(50)
    ,BATCH_TASK_START_TIMESTAMP    TIMESTAMP
    ,BATCH_TASK_END_TIMESTAMP      TIMESTAMP
    );
/