CREATE OR REPLACE FORCE VIEW G77_CFG.VDMP_FINANCE_DATA
(REC_ID
,METADATA_ID
,MAPPING_TABLE
,SOURCE_SYSTEM_CODE
,SOURCE_DATA_1
,SOURCE_DATA_1_DESC
,MODIFIED_BY
,MODIFIED_ON
,APPROVED_BY
,ACTIVE_INDICATOR
)
BEQUEATH DEFINER
AS
  SELECT fin.GATEWAY_ID         as REC_ID
       , fin.ATTRIBUTE_NBR    
       , fin.ATTRIBUTE_ID  
       , 'G77'                  as SOURCE_SYSTEM_CODE   
       , fin.ATTRIBUTE_VALUE  
       , fin.VALUE_DESCRIPTION
       , fin.INPUT_BY
       , fin.INPUT_TIME
       , fin.APPROVED_BY
       , fin.ACTIVE_INDICATOR
    FROM REF_FINANCE_DATA fin
ORDER BY fin.ATTRIBUTE_NBR;
