create or replace view g77_cfg.v_meta_batch_task_status as
select
  BATCH_TASK_SESSION_ID         as SESSION_ID
, BATCH_TASK_USE_CASE_ID        as USE_CASE_ID
, BATCH_TASK_UC4_RUN_ID         as UC4_RUN_ID
, BATCH_TASK_APTITUDE_PROJECT   as APTITUDE_PROJECT
, BATCH_TASK_APTITUDE_MICROFLOW as APTITUDE_MICROFLOW
, BATCH_TASK_STATUS             as STATUS
, BATCH_TASK_COMPLETED          as COMPLETED
, BATCH_TASK_RECORDS_PROCESSED  as PROCESSED
, BATCH_TASK_RECORDS_SUCCESSFUL as SUCCESS
, BATCH_TASK_RECORDS_IN_ERROR   as ERROR
, BATCH_TASK_START_TIMESTAMP    as START_TSP
, BATCH_TASK_END_TIMESTAMP      as END_TSP
, round ((NVL (BATCH_TASK_END_TIMESTAMP, SYSTIMESTAMP) - BATCH_TASK_START_TIMESTAMP) * 60 * 60 * 24) as ELAPSED_IN_SEC
, round ((NVL (BATCH_TASK_END_TIMESTAMP, SYSTIMESTAMP) - BATCH_TASK_START_TIMESTAMP) * 60 * 24) as ELAPSED_IN_MIN
, round ((NVL (BATCH_TASK_END_TIMESTAMP, SYSTIMESTAMP) - BATCH_TASK_START_TIMESTAMP) * 24) as ELAPSED_IN_H
, DMP_ERROR_ACTIVE_INDICATOR    as DMP_ERROR_ACTIVE_INDICATOR
from g77_cfg.t_batch_task_status
where NOT (BATCH_TASK_COMPLETED = 'Y' and BATCH_TASK_END_TIMESTAMP is null)
;
