CREATE TABLE DQ_USER.T_BATCH_TASK_STATUS
(
    BATCH_TASK_PROCESS_ID           NUMBER(12),
    BATCH_TASK_ID                   NUMBER NOT NULL,
    BATCH_TASK_UC4_RUN_ID           NUMBER, 
    BATCH_TASK_APTITUDE_PROJECT     VARCHAR2(240 BYTE) NOT NULL,
    BATCH_TASK_APTITUDE_MICROFLOW   VARCHAR2(240 BYTE) NOT NULL,
    BATCH_TASK_SESSION_ID           VARCHAR2(240 BYTE) NOT NULL,
    BATCH_TASK_USE_CASE_ID          VARCHAR2(240 BYTE) NOT NULL,
    BATCH_TASK_STATUS               CHAR(1 BYTE)       NOT NULL,
    BATCH_TASK_COMPLETED            CHAR(1 BYTE)       NOT NULL,
    BATCH_TASK_RECORDS_PROCESSED    NUMBER(12),
    BATCH_TASK_RECORDS_SUCCESSFUL   NUMBER(12),
    BATCH_TASK_RECORDS_IN_ERROR     NUMBER(12),
    BATCH_TASK_START_TIMESTAMP      DATE,
    BATCH_TASK_END_TIMESTAMP        DATE,
    DMP_ERROR_ACTIVE_INDICATOR      CHAR(1 BYTE),
  CONSTRAINT PK_T_BATCH_TASK_STATUS PRIMARY KEY (BATCH_TASK_PROCESS_ID)
);
