CREATE TABLE DQ_USER.T_DQ_SEVERITY
(
 DQ_SEVERITY_ID       NUMBER(1)           NOT NULL
,DQ_SEVERITY          VARCHAR2(50 BYTE)   NOT NULL
,DQ_SEVERITY_DESC     VARCHAR2(1000 BYTE)
,CONSTRAINT PK_T_DQ_SEVERITY PRIMARY KEY (DQ_SEVERITY_ID)
);