create table DQ_USER.t_task_cfg
(
   t_task_cfg_id number generated by default on null as identity (start with 1 order)
  ,task_name varchar2(4000) not null
  ,max_workers number not null
  ,constraint pk_t_task_cfg primary key(t_task_cfg_id)
);
