CREATE OR REPLACE TRIGGER DQ_USER.TR_T_ERROR_LOG_ACTIV_IND
BEFORE INSERT
ON DQ_USER.T_ERROR_LOG REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  IF :new.ERROR_ACTIVE_IND IS NULL THEN
     :new.ERROR_ACTIVE_IND := 'A';
  END IF;
END;
/