CREATE OR REPLACE FORCE VIEW DQ_USER.VDMP_FINANCE_DATA_UPD_HIST
(REC_ID
,METADATA_ID
,UPDATE_COUNT
,MODIFIED_BY
,MODIFIED_ON
,APPROVED_BY
,SOURCE_DATA_1
,SOURCE_DATA_1_DESC
,REQUEST_TYPE
,REQUEST_COUNT
)
BEQUEATH DEFINER
AS
SELECT dmp_row_id rec_id
     , metadata_id
     , update_count
     , modified_by
     , modified_time MODIFIED_ON
     , approved_by
     , source_system_value1 SOURCE_DATA_1
     , source_system_value1_desc SOURCE_DATA_1_DESC
     , REQUEST_TYPE
     , REQUEST_COUNT
FROM T_DMP_FINANCE_UPD_HIST;