CREATE OR REPLACE FUNCTION G77_CFG.FN_DQIS_DATE (p_string IN VARCHAR2,p_date_format IN VARCHAR2)
   RETURN VARCHAR2
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
  v_date DATE; 
BEGIN
   v_date := TO_DATE(p_string,p_date_format);
   RETURN 'SUCCESS';
EXCEPTION
WHEN OTHERS THEN
   RETURN 'DQERROR';
END FN_DQIS_DATE;
/