CREATE OR REPLACE FUNCTION G77_CFG.FN_DQISNOTNULL_STRING (p_string VARCHAR2)
RETURN VARCHAR2
   DETERMINISTIC
   PARALLEL_ENABLE
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

  IF p_string IS NULL THEN
    RETURN 'DQERROR';
  ELSE
    RETURN 'SUCCESS';
  END IF;
EXCEPTION
WHEN OTHERS THEN
   RETURN 'DQERROR';    
END ;
/
