CREATE TABLE DQ_USER.T_DMP_FINANCE_WF_DATA
    (METADATA_ID                   NUMBER              NOT NULL
    ,MODIFIED_BY                   VARCHAR2(100 CHAR)
    ,MODIFIED_TIME                 DATE
    ,CONSTRAINT PK_DMP_FINANCE_WF_DATA PRIMARY KEY (METADATA_ID)
);