CREATE TABLE DQ_USER.T_DMP_FINANCE_ACCESS_DATA
    (METADATA_ID                   NUMBER NOT NULL
    ,ROLE_NAME                     VARCHAR2(255 BYTE)
    ,MODIFIED_BY                   VARCHAR2(100 CHAR)
    ,MODIFIED_TIME                 DATE
    ,CONSTRAINT PK_DMP_FINANCE_ACCESS_DATA PRIMARY KEY (METADATA_ID,ROLE_NAME)
);