CREATE TABLE DQ_USER.T_DMP_USE_CASE_CATEGORY 
    (CATEGORY_NAME                 VARCHAR2(200 BYTE)
    ,CATEGORY_GROUP                VARCHAR2(200 BYTE)
    ,DESCRIPTION                   VARCHAR2(200 BYTE)
    ,CONSTRAINT PK_T_DMP_USE_CASE_CATEGORY PRIMARY KEY (CATEGORY_NAME)
);