@@t_batch_task_status.sql
@@t_batch_task_status_aud.sql
@@t_build_history.sql
@@t_build_log.sql
@@t_build_version.sql
@@t_dq_condition.sql
@@t_dq_error_messages.sql
@@t_dq_function.sql
@@t_dq_log.sql
@@t_dq_severity.sql
@@t_dq_threshold.sql
@@t_error_log.sql
@@t_error_log_aud.sql
@@t_file_config.sql
@@t_file_control.sql
@@t_info_log.sql
@@t_meta_batch_task.sql
@@t_meta_batch_task_table_x.sql
@@t_meta_interface.sql
@@t_meta_interface_aud.sql
@@t_meta_table.sql
@@t_meta_table_dq.sql
@@t_meta_table_dq_aud.sql
@@t_null_handling.sql
@@t_privs_config.sql
@@t_task_cfg.sql
@@t_task_list.sql
@@t_task_worker.sql