CREATE TABLE G77_CFG.T_DQ_CONDITION
(
 DQ_CONDITION_ID    NUMBER(12)          NOT NULL
,DQ_TABLE_NAME      VARCHAR2(30 BYTE)   NOT NULL
,DQ_CONDITION       VARCHAR2(4000 BYTE) NOT NULL
,DQ_CONDITION_DESC  VARCHAR2(1000 BYTE)
,CREATE_DATE	      DATE                NOT NULL
,LAST_UPDATED	      DATE
,USER_ID            VARCHAR2(50 BYTE)   NOT NULL
,CONSTRAINT PK_T_DQ_CONDITION PRIMARY KEY (DQ_CONDITION_ID)
);