CREATE TABLE G77_CFG.T_DQ_FUNCTION
(
 DQ_FUNCTION_ID            NUMBER (12)         NOT NULL
,DQ_FUNCTION	             VARCHAR2(30 BYTE)   NOT NULL
,DQ_FUNCTION_DESC	         VARCHAR2(1000 BYTE)
,CREATE_DATE	             DATE                DEFAULT SYSDATE
,LAST_UPDATED	             DATE
,USER_ID                   VARCHAR2(50 BYTE)   DEFAULT USER
,CONSTRAINT PK_T_DQ_FUNCTION PRIMARY KEY (DQ_FUNCTION_ID)
);