CREATE TABLE G77_CFG.T_INFO_LOG
(
EVENT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 CACHE 1000 NOORDER) ,
  EVENT_DATETIME              DATE                NOT NULL,
  APTITUDE_PROJECT            VARCHAR2(50 BYTE)   NOT NULL,
  RULE_IDENT                  VARCHAR2(100 BYTE)  NOT NULL,
  MESSAGE_TEXT                VARCHAR2(4000 BYTE) NOT NULL,
  SOURCE_SYSTEM               VARCHAR2(10 BYTE)           ,
  TARGET_SYSTEM               VARCHAR2(10 BYTE)           ,  
  SOURCE_TABLE                VARCHAR2(100 BYTE)          ,
  BATCH_PROCESS_ID            NUMBER(12)                  ,
  USE_CASE_ID                 VARCHAR2(200 BYTE)          ,
  SESSION_ID                  VARCHAR2(200 BYTE)          ,
  GATEWAY_ID                  NUMBER                      ,
  SOURCE_SYSTEM_ID            VARCHAR2(50 BYTE)           ,
  PARENT_SOURCE_ID            VARCHAR2(50 BYTE)           ,
  CONSTRAINT PK_T_INFO_LOG PRIMARY KEY (EVENT_ID)
);
