CREATE TABLE G77_CFG.T_NULL_HANDLING 
    (DATA_TYPE                     VARCHAR2(100 BYTE)
    ,HANDLING_STRING               VARCHAR2(100 BYTE)
    ,TO_FUNCTION                   VARCHAR2(100 BYTE)
    ,FUNCTION_CLOSE                VARCHAR2(100 BYTE)
    ,CONSTRAINT PK_T_NULL_HANDLING PRIMARY KEY (DATA_TYPE)
    );