CREATE TABLE G77_CFG.T_PRIVS_CONFIG
(
  USER_OR_ROLE_NAME     VARCHAR2(30) NOT NULL
 ,OBJECT_NAME           VARCHAR2(30) NOT NULL  
 ,OBJECT_TYPE           VARCHAR2(30) NOT NULL CHECK (OBJECT_TYPE IN ('TABLE','VIEW','FUNCTION','PROCEDURE','PACKAGE','SEQUENCE'))
 ,PRIVILEGE             VARCHAR2(100) NOT NULL
 ,CONSTRAINT PK_T_PRIVS_CONFIG PRIMARY KEY (USER_OR_ROLE_NAME, OBJECT_TYPE, OBJECT_NAME)
);