create table g77_cfg.t_task_list
(
   t_task_list_id number generated by default on null as identity (start with 1 order)
  ,task_name varchar2(4000) not null
  ,task_priority number not null
  ,start_from date not null
  ,start_to date not null
  ,task_status number not null
  ,vcparam1 varchar2(4000)
  ,vcparam2 varchar2(4000)
  ,vcparam3 varchar2(4000)
  ,vcparam4 varchar2(4000)
  ,vcparam5 varchar2(4000)
  ,vcparam6 varchar2(4000)
  ,vcparam7 varchar2(4000)
  ,vcparam8 varchar2(4000)
  ,vcparam9 varchar2(4000)
  ,vcparam10 varchar2(4000)
  ,nrparam1 number
  ,nrparam2 number
  ,nrparam3 number
  ,nrparam4 number
  ,nrparam5 number
  ,dtparam1 date
  ,dtparam2 date
  ,dtparam3 date
  ,dtparam4 date
  ,dtparam5 date
  ,tsparam1 timestamp
  ,tsparam2 timestamp
  ,tsparam3 timestamp
  ,tsparam4 timestamp
  ,tsparam5 timestamp
  ,cr_time date not null
  ,md_time date
  ,constraint pk_t_task_list primary key(t_task_list_id)
)
partition by list(task_status) ( 
  partition p_1 values (1),
  partition p_2 values (2),
  partition p_3 values (3),
  partition p_4 values (4),
  partition p_5 values (5),
  partition p_6 values (6),
  partition p_7 values (7),
  partition p_8 values (8),
  partition p_9 values (9),
  partition p_10 values (10),
  partition p_default values (default) ) enable row movement;
;
comment on column g77_cfg.t_task_list.t_task_list_id is 'PK';
comment on column g77_cfg.t_task_list.task_name is 'task name to execute';
comment on column g77_cfg.t_task_list.task_priority is 'task priority, higher value = higher priority';
comment on column g77_cfg.t_task_list.start_from is 'task can be started between start_from and start_to';
comment on column g77_cfg.t_task_list.start_to is 'task can be started between start_from and start_to';
comment on column g77_cfg.t_task_list.task_status is 'task status';
